include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_web_libraries_in_flutter: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    library_private_types_in_public_api: false
    always_declare_return_types: true
    empty_catches: true
    file_names: true
    flutter_style_todos: true
    omit_local_variable_types: true
    prefer_final_locals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_constructors_first: true
    type_annotate_public_apis: true
    unawaited_futures: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_dynamic_calls: true
    avoid_double_and_int_checks: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_returning_null: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    cascade_invocations: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_default_cases: true
    null_check_on_nullable_type_parameter: true
    one_member_abstracts: true
    only_throw_errors: true
    package_api_docs: true
    cast_nullable_to_non_nullable: true
    close_sinks: true
    comment_references: true
    deprecated_consistency: true
    directives_ordering: true
    join_return_with_assignment: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_foreach: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    require_trailing_commas: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    tighten_type_of_initializing_formals: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
