import 'dart:io';

import 'package:youtube_explode_dart/youtube_explode_dart.dart';

const videoList = [
  'https://www.youtube.com/watch?v=O6_hhiqXAFU&list=PLT-tOjYQy3-bQeFgIumqhsWRutfBkvENU&index=1&pp=iAQB',
  'https://www.youtube.com/watch?v=MyFDbSAtqMk&list=PLT-tOjYQy3-bQeFgIumqhsWRutfBkvENU&index=2&pp=iAQB',
  'https://www.youtube.com/watch?v=YqMceCvgVHQ&list=PLT-tOjYQy3-bQeFgIumqhsWRutfBkvENU&index=3&pp=iAQB',
  'https://www.youtube.com/watch?v=Dxf6WmPnMA8&list=PLT-tOjYQy3-bQeFgIumqhsWRutfBkvENU&index=4&pp=iAQB',
  'https://www.youtube.com/watch?v=aMWnpkscjU0&list=PLT-tOjYQy3-bQeFgIumqhsWRutfBkvENU&index=7&pp=iAQB',
  'https://www.youtube.com/watch?v=zGINo3BloGo&list=PLT-tOjYQy3-bQeFgIumqhsWRutfBkvENU&index=11&pp=iAQB',
  'https://www.youtube.com/watch?v=rC3EAxfK-Ok&list=PLT-tOjYQy3-bQeFgIumqhsWRutfBkvENU&index=14&pp=iAQB',
  'https://www.youtube.com/watch?v=RTwP6ADg80A&list=PLT-tOjYQy3-bQeFgIumqhsWRutfBkvENU&index=15&pp=iAQB',
  'https://www.youtube.com/watch?v=G-tAp7EiawQ&list=PLT-tOjYQy3-bQeFgIumqhsWRutfBkvENU&index=20&pp=iAQB',
  'https://www.youtube.com/watch?v=OVOKCEZRf8M&list=PLT-tOjYQy3-bQeFgIumqhsWRutfBkvENU&index=32&pp=iAQB',
  'https://www.youtube.com/watch?v=d-4eVMv59y8&list=PLT-tOjYQy3-ZP1wDEOtNDQLKz2ws7gV80&index=2&pp=iAQB',
  'https://www.youtube.com/watch?v=T8okvmlZYIQ&list=PLT-tOjYQy3-ZP1wDEOtNDQLKz2ws7gV80&index=7&pp=iAQB',
  'https://www.youtube.com/watch?v=YuN45xyP3FM&list=PLT-tOjYQy3-ZP1wDEOtNDQLKz2ws7gV80&index=10&pp=iAQB',
  'https://www.youtube.com/watch?v=S8CHxTG8S9M&list=PLT-tOjYQy3-a2HjGSI7ZkUqwhvIDLyhku&index=2&pp=iAQB',
  'https://www.youtube.com/watch?v=PFriZQww71I&list=PLT-tOjYQy3-a2HjGSI7ZkUqwhvIDLyhku&index=1&pp=iAQB',
  'https://www.youtube.com/watch?v=Ugb1fItFqfM&list=PL2eWdUqM6485SFEiper-gKt5p4wzzatcJ&index=1&pp=iAQB',
  'https://www.youtube.com/watch?v=DlRCFD2n3Bo&list=PL2eWdUqM6485SFEiper-gKt5p4wzzatcJ&index=2&pp=iAQB',
  'https://www.youtube.com/watch?v=cbyT1_yr-4M&list=PL2eWdUqM6485SFEiper-gKt5p4wzzatcJ&index=8&pp=iAQB',
  'https://www.youtube.com/watch?v=-o4sXCOWPG0',
  'https://www.youtube.com/watch?v=bpwEtp5nduE',
  'https://www.youtube.com/watch?v=Htx4WdeNyRk',
  'https://www.youtube.com/watch?v=JV01gDMvl6U',
  'https://www.youtube.com/watch?v=bVb3wL_cvCU',
  'https://www.youtube.com/watch?v=qttk0B1xqBs',
  'https://www.youtube.com/watch?v=EDCpUF1wN-4',
  'https://www.youtube.com/watch?v=bAsZCMZzbl8',
  'https://www.youtube.com/watch?v=FhP3u1DY8pI',
  'https://www.youtube.com/watch?v=QzkajD1GMGQ',
  'https://www.youtube.com/watch?v=q-GNygaYiZk',
  'https://www.youtube.com/watch?v=OlJTEvGnsuw',
  'https://www.youtube.com/watch?v=aDusU_FoGPI',
  'https://www.youtube.com/watch?v=un4pcy5yRLI',
  'https://www.youtube.com/watch?v=8iX--CK7i9c',
  'https://www.youtube.com/watch?v=dVFnLbXKFwg',
  'https://www.youtube.com/watch?v=P60JO-2pAq4&list=PL081Qy7d3NdtWp-YklGd-8_7foKiJJefu&index=1&pp=iAQB',
  'https://www.youtube.com/watch?v=jcwq57fyw1Y&list=PL081Qy7d3NdtWp-YklGd-8_7foKiJJefu&index=2&pp=iAQB',
  'https://www.youtube.com/watch?v=HQmxA5pTq6w&list=PL081Qy7d3NdtWp-YklGd-8_7foKiJJefu&index=3&pp=iAQB',
  'https://www.youtube.com/watch?v=GTbYhKFIHqk&list=PL081Qy7d3NdtPig-XYxOXZFgFe7HhoDUL&index=1&pp=iAQB',
  'https://www.youtube.com/watch?v=FVkqntoOeac&list=PL081Qy7d3NdtPig-XYxOXZFgFe7HhoDUL&index=2&pp=iAQB',
  'https://www.youtube.com/watch?v=xMAGvn4s8Tg&list=PL081Qy7d3NdtPig-XYxOXZFgFe7HhoDUL&index=3&pp=iAQB',
  'https://www.youtube.com/watch?v=vuC3JEkgFVU&list=PL081Qy7d3NdtPig-XYxOXZFgFe7HhoDUL&index=4&pp=iAQB',
  'https://www.youtube.com/watch?v=uHaetTkx-_g&list=PL081Qy7d3NdtPig-XYxOXZFgFe7HhoDUL&index=5&pp=iAQB',
  'https://www.youtube.com/watch?v=ZVqQtbhQbC0&list=PL081Qy7d3NdtPig-XYxOXZFgFe7HhoDUL&index=7&pp=iAQB',
  'https://www.youtube.com/watch?v=IFf1lRv2LoE&list=PL081Qy7d3NdschWQL6vO4bhaJ_ro2iIVm&index=1&pp=iAQB',
  'https://www.youtube.com/watch?v=Es9fZ-oejCo&list=PL081Qy7d3NdschWQL6vO4bhaJ_ro2iIVm&index=4&pp=iAQB',
  'https://www.youtube.com/watch?v=UbbF23XtF84&list=PL081Qy7d3NdschWQL6vO4bhaJ_ro2iIVm&index=6&pp=iAQB',
  'https://www.youtube.com/watch?v=XiSnqxqKgek&list=PL081Qy7d3NdschWQL6vO4bhaJ_ro2iIVm&index=7&pp=iAQB',
  'https://www.youtube.com/watch?v=d3ffO68pQhU&list=PL081Qy7d3NdschWQL6vO4bhaJ_ro2iIVm&index=11&pp=iAQB',
  'https://www.youtube.com/watch?v=COY3JsfqTuU&list=PL081Qy7d3NdschWQL6vO4bhaJ_ro2iIVm&index=14&pp=iAQB',
  'https://www.youtube.com/watch?v=ZmN056TPPIM&list=PL081Qy7d3NdschWQL6vO4bhaJ_ro2iIVm&index=17&pp=iAQB',
  'https://www.youtube.com/watch?v=xhTqpgB1mZA',
  'https://www.youtube.com/watch?v=me3SBW7RMxA',
  'https://www.youtube.com/watch?v=0WwTBKG8lU8',
  'https://www.youtube.com/watch?v=u9xNb_y-c5w',
  'https://www.youtube.com/watch?v=Ud6G9HOpznI',
  'https://www.youtube.com/watch?v=_vR_6c65Jck',
  'https://www.youtube.com/watch?v=PoKWEKY5lTg',
  'https://www.youtube.com/watch?v=9e29r--lBy4',
  'https://www.youtube.com/watch?v=beExmUUyNqc',
  'https://www.youtube.com/watch?v=zh0WzDFNYW4',
  'https://www.youtube.com/watch?v=-Is44yj78p8',
  'https://www.youtube.com/watch?v=m43rzWc4yIA',
  'https://www.youtube.com/watch?v=CmHQzvjrwt8',
  'https://www.youtube.com/watch?v=DvoSheel_C8',
  'https://www.youtube.com/watch?v=QYRNWXJcgqc',
  'https://www.youtube.com/watch?v=fsYAZlyzFKU',
  'https://www.youtube.com/watch?v=hsivfcT3ceg',
  'https://www.youtube.com/watch?v=ANObtGRomYg',
  'https://www.youtube.com/watch?v=upbMaKNR4Sg',
  'https://www.youtube.com/watch?v=zJrAe_aPucM',
  'https://www.youtube.com/watch?v=nbwgaj_PmAA',
  'https://www.youtube.com/watch?v=rja_clyOupU',
  'https://www.youtube.com/watch?v=4n3fMhK9hEg',
  'https://www.youtube.com/watch?v=BE9ya1tUroA',
  'https://www.youtube.com/watch?v=be9xoVJY2yw',
  'https://www.youtube.com/watch?v=SNiJv4EVvxI',
  'https://www.youtube.com/watch?v=Wtn_HAjb4wo',
  'https://www.youtube.com/watch?v=IVFdFTJS0T4',
  'https://www.youtube.com/watch?v=K9woFCSroSs',
  'https://www.youtube.com/watch?v=Yur213k1wfg',
  'https://www.youtube.com/watch?v=yTrM46M1eA4',
  'https://www.youtube.com/watch?v=3f9BCgXK_k4',
  'https://www.youtube.com/watch?v=bXe4DWC6ISU',
  'https://www.youtube.com/watch?v=ZVqJkuaLyMo',
  'https://www.youtube.com/watch?v=5CV8xVMUt-8',
  'https://www.youtube.com/watch?v=e5hyg-pUTM0',
  'https://www.youtube.com/watch?v=pvNw9XkTW2M',
  'https://www.youtube.com/watch?v=dCgQ2-i4R2g',
  'https://www.youtube.com/watch?v=_QbTT1Y4Ba8',
  'https://www.youtube.com/watch?v=EUgKARq8eTQ',
  'https://www.youtube.com/watch?v=1d3vrR5_Qj8',
  'https://www.youtube.com/watch?v=WuF3TLtUjmA',
  'https://www.youtube.com/watch?v=bDSfYKwZ7Po',
  'https://www.youtube.com/watch?v=nf9K96E39ss',
  'https://www.youtube.com/watch?v=olsYx-z9V4M',
  'https://www.youtube.com/watch?v=MuaSbV_7lfk',
  'https://www.youtube.com/watch?v=__DuSb-8bYY',
  'https://www.youtube.com/watch?v=ye9VfX0hwbU',
  'https://www.youtube.com/watch?v=STGsQ2ewyeQ',
  'https://www.youtube.com/watch?v=VljhWyqD7YE',
  'https://www.youtube.com/watch?v=y14myUsAnYM',
  'https://www.youtube.com/watch?v=b21nnbzegyM',
  'https://www.youtube.com/watch?v=2uUPWBvFB1I',
  'https://www.youtube.com/watch?v=vYbB5EL7TFc',
  'https://www.youtube.com/watch?v=vVLSbV6kfFc',
  'https://www.youtube.com/watch?v=FGb8zXYmFfw',
  'https://www.youtube.com/watch?v=E-kY8XxyY0w',
  'https://www.youtube.com/watch?v=dS5ltWwru2o',
  'https://www.youtube.com/watch?v=0aBGx_XdxRo',
  'https://www.youtube.com/watch?v=_MpxvZJ8egk',
  'https://www.youtube.com/watch?v=xPbA574Wuj4',
  'https://www.youtube.com/watch?v=yzN4Vgo35pA',
  'https://www.youtube.com/watch?v=1fD2nhqQ3hM',
  'https://www.youtube.com/watch?v=FGb8zXYmFfw',
  'https://www.youtube.com/watch?v=_X6gitFTf1w',
  'https://www.youtube.com/watch?v=918dzJSZeRY',
  'https://www.youtube.com/watch?v=M3Mqu_iS9ws',
  'https://www.youtube.com/watch?v=TRZm624_aiA',
  'https://www.youtube.com/watch?v=KVdE21yrVLg',
  'https://www.youtube.com/watch?v=f6eFvdVikVs',
  'https://www.youtube.com/watch?v=9ht5WBeOtIo',
  'https://www.youtube.com/watch?v=Qjch8ze8sQM',
  'https://www.youtube.com/watch?v=mxWpx42T56I',
  'https://www.youtube.com/watch?v=M7r9v0yQGbQ',
  'https://www.youtube.com/watch?v=ELkc3M5T300',
  'https://www.youtube.com/watch?v=_lShbLCQy6g',
  'https://www.youtube.com/watch?v=V7fJjoBiMBM',
  'https://www.youtube.com/watch?v=BdhD8of_uvw',
  'https://www.youtube.com/watch?v=8OnYhyzJdb0',
  'https://www.youtube.com/watch?v=58ewn201Z1s',
  'https://www.youtube.com/watch?v=1zvfCs22HDQ',
  'https://www.youtube.com/watch?v=DkJg6TDLYqk',
  'https://www.youtube.com/watch?v=hge3fr50o0o',
  'https://www.youtube.com/watch?v=u-wS8jABqQI&t=1s',
  'https://www.youtube.com/watch?v=o5vb430_m38',
  'https://www.youtube.com/watch?v=n5Sl3zSvIUQ',
  'https://www.youtube.com/watch?v=fyZETx-5c2o',
  'https://www.youtube.com/watch?v=Ov-0-RS9zDg',
  'https://www.youtube.com/watch?v=JYHS1rDXxM0',
  'https://www.youtube.com/watch?v=uTh0-kdt374',
  'https://www.youtube.com/watch?v=nhGh9N0baQA',
  'https://www.youtube.com/watch?v=cQsupVhKcDg',
  'https://www.youtube.com/watch?v=qzP23uZVqVw',
  'https://www.youtube.com/watch?v=_8peDwA_pg4',
  'https://www.youtube.com/watch?v=LARsdRVCvHU',
  'https://www.youtube.com/watch?v=-J5dKNSvBnE',
  'https://www.youtube.com/watch?v=2P51OQIhn_M',
  'https://www.youtube.com/watch?v=Eg8ur-vCv9c',
  'https://www.youtube.com/watch?v=JTwrsgSi9HA',
  'https://www.youtube.com/watch?v=lJHuZvjYVI8',
  'https://www.youtube.com/watch?v=EGdxsOPgr7A',
  'https://www.youtube.com/watch?v=dbeRdn_mfwI',
  'https://www.youtube.com/watch?v=wuscXvUWABw',
  'https://www.youtube.com/watch?v=P5OAjl5FvbY',
  'https://www.youtube.com/watch?v=7IecImX6hy8',
  'https://www.youtube.com/watch?v=ErRpVQQPeSA',
  'https://www.youtube.com/watch?v=zT_bGSmfp10',
  'https://www.youtube.com/watch?v=AEBhN-RWMMQ',
  'https://www.youtube.com/watch?v=Xy1N-wevl4c',
  'https://www.youtube.com/watch?v=-E4Aqwg-tCo',
  'https://www.youtube.com/watch?v=aQdJ8vvoI_M',
  'https://www.youtube.com/watch?v=WDxJDdDcBV0',
  'https://www.youtube.com/watch?v=VhUP0UukC0Y',
  'https://www.youtube.com/watch?v=kyT8eq9Sl_s',
  'https://www.youtube.com/watch?v=IVyJHWtgFYs',
  'https://www.youtube.com/watch?v=aiTrIkRdxQk',
  'https://www.youtube.com/watch?v=LQeue6RlrXc',
  'https://www.youtube.com/watch?v=z-_CSfrHnzM',
  'https://www.youtube.com/watch?v=bJRFsIrXIlU',
  'https://www.youtube.com/watch?v=Vo-8UBRhUYM',
  'https://www.youtube.com/watch?v=2YbPyR8ZKyo',
  'https://www.youtube.com/watch?v=cSHAolzmFkA&t=17s',
  'https://www.youtube.com/watch?v=wwWkSrVeD7c',
  'https://www.youtube.com/watch?v=fj2EfhSSqas',
  'https://www.youtube.com/watch?v=qwvhtADNQNg',
  'https://www.youtube.com/watch?v=lkrT5hjv3cg',
  'https://www.youtube.com/watch?v=NIFDpprdz3Y',
  'https://www.youtube.com/watch?v=rOtV4PU4mQ4',
  'https://www.youtube.com/watch?v=oqJ_10R9vqY',
  'https://www.youtube.com/watch?v=OfkXSB-ci0M',
  'https://www.youtube.com/watch?v=huoV5y6kerY',
  'https://www.youtube.com/watch?v=cu2XoxJgMvo',
  'https://www.youtube.com/watch?v=z3J6FXik1gU',
  'https://www.youtube.com/watch?v=D7dDiKgqOIo',
  'https://www.youtube.com/watch?v=NGqqEflItpc',
  'https://www.youtube.com/watch?v=APtxgoW0bds',
  'https://www.youtube.com/watch?v=bDSfYKwZ7Po',
  'https://www.youtube.com/watch?v=nOnrk94_Dj8',
  'https://www.youtube.com/watch?v=BzBdLkJ9Wi0',
  'https://www.youtube.com/watch?v=ByqK5ov8qao',
  'https://www.youtube.com/watch?v=nbwgaj_PmAA',
  'https://www.youtube.com/watch?v=rja_clyOupU',
  'https://www.youtube.com/watch?v=4xBYv-nKT1c',
  'https://www.youtube.com/watch?v=BLkOkVCcZZQ',
  'https://www.youtube.com/watch?v=7pGIF24guv0',
  'https://www.youtube.com/watch?v=4n3fMhK9hEg',
  'https://www.youtube.com/watch?v=YBVew3rcEa8',
  'https://www.youtube.com/watch?v=Dqm79X5SV-Q',
  'https://www.youtube.com/watch?v=uveZX-71OUw',
  'https://www.youtube.com/watch?v=le-G-jUKWR8',
  'https://www.youtube.com/watch?v=JAkx_q-D4Ws',
  'https://www.youtube.com/watch?v=h-QWVyg6YaM',
  'https://www.youtube.com/watch?v=77L0ml0x5-w',
  'https://www.youtube.com/watch?v=QOH1y0t6jIQ',
  'https://www.youtube.com/watch?v=0-s2HpY__JE',
  'https://www.youtube.com/watch?v=_bj20ycckZY',
  'https://www.youtube.com/watch?v=VhpZNDR5T8U',
  'https://www.youtube.com/watch?v=-Is44yj78p8',
  'https://www.youtube.com/watch?v=gxqRXL48M6Q',
  'https://www.youtube.com/watch?v=1o0MCulPIz8',
  'https://www.youtube.com/watch?v=lNvo9ur4QhA',
  'https://www.youtube.com/watch?v=oPdjhsW46c4',
  'https://www.youtube.com/watch?v=7qFOpcN5oGQ',
  'https://www.youtube.com/watch?v=QDh498hTYnc',
  'https://www.youtube.com/watch?v=dRwP0sYQO4Q',
  'https://www.youtube.com/watch?v=VZhsYRvu508',
  'https://www.youtube.com/watch?v=X_dUYiIuxeo',
  'https://www.youtube.com/watch?v=PCGD4hZYufg',
  'https://www.youtube.com/watch?v=gxqRXL48M6Q',
  'https://www.youtube.com/watch?v=VzUaVBXGVeQ',
  'https://www.youtube.com/watch?v=BMwXyc1yomA',
  'https://www.youtube.com/watch?v=kbmj-28AQgc',
  'https://www.youtube.com/watch?v=f6CeYdgX02U',
  'https://www.youtube.com/watch?v=Y-Wch_hJiAE',
  'https://www.youtube.com/watch?v=vN4cb1hlw_A',
  'https://www.youtube.com/watch?v=_qZccBRFm6I',
  'https://www.youtube.com/watch?v=YcBTgwsB-1E',
  'https://www.youtube.com/watch?v=bDSjv4JJRhM',
  'https://www.youtube.com/watch?v=Fx12MRw9bqw',
  'https://www.youtube.com/watch?v=HNSN12Kda20',
  'https://www.youtube.com/watch?v=vW9giSuTepY',
  'https://www.youtube.com/watch?v=rYMR13OeX-c',
  'https://www.youtube.com/watch?v=z0-rJigZnPM',
  'https://www.youtube.com/watch?v=lfelRMHGMWk',
  'https://www.youtube.com/watch?v=LJ4_b5OML8E',
  'https://www.youtube.com/watch?v=zT9OaUo2GuE',
  'https://www.youtube.com/watch?v=csteZarRUVU',
  'https://www.youtube.com/watch?v=Cqk-tF55ct0',
  'https://www.youtube.com/watch?v=Y5LI019OX_c',
  'https://www.youtube.com/watch?v=qVvkOAWptAI',
  'https://www.youtube.com/watch?v=SfMd9P6t_zc',
  'https://www.youtube.com/watch?v=WLuoPEfqTUg',
  'https://www.youtube.com/watch?v=5S7RqsDCdNQ',
  'https://www.youtube.com/watch?v=T4lwZDCiPsA',
  'https://www.youtube.com/watch?v=qpld6cuBn5I',
  'https://www.youtube.com/watch?v=31nCMPj_8EA',
  'https://www.youtube.com/watch?v=zshgMDYy_WQ',
  'https://www.youtube.com/watch?v=fQGy3Zee4xI',
  'https://www.youtube.com/watch?v=9iZKmhi4h38',
  'https://www.youtube.com/watch?v=lHZ0B5Aqu7Y',
  'https://www.youtube.com/watch?v=Vi4ToA9PdkQ',
  'https://www.youtube.com/watch?v=Y2HmzUscgZQ',
  'https://www.youtube.com/watch?v=aIEPiaqLLIg',
  'https://www.youtube.com/watch?v=-HJHu_IzkNY',
  'https://www.youtube.com/watch?v=wYGGp01f9LU',
  'https://www.youtube.com/watch?v=J_YyeQAsSvI',
  'https://www.youtube.com/watch?v=A99tjjnJiG8',
  'https://www.youtube.com/watch?v=FlVJENhV3iI',
  'https://www.youtube.com/watch?v=5bfs4RgR3MA',
  'https://www.youtube.com/watch?v=WdAaDprWlCY',
  'https://www.youtube.com/watch?v=Y6vEyLN76qs',
  'https://www.youtube.com/watch?v=GVrxkycUmwI',
  'https://www.youtube.com/watch?v=JJy2hWtyvos',
  'https://www.youtube.com/watch?v=3jGWu2JyVX4',
  'https://www.youtube.com/watch?v=0Z8vYVQ72MI',
  'https://www.youtube.com/watch?v=XLR1pnZ_GfQ',
  'https://www.youtube.com/watch?v=7JPvtwOPBPM',
  'https://www.youtube.com/watch?v=rLrQwKltvs0',
  'https://www.youtube.com/watch?v=J6IHBAa0fPc',
  'https://www.youtube.com/watch?v=eWarSIa0GI4',
];

Future<void> main() async {
  final youtube = YoutubeExplode();
  // CSVファイルのパス
  final csvFile = File('lib/youtube.csv');
  // CSVファイルのヘッダー
  const headers = 'thumbnailUrl,title,linkUrl\n';

  // 新しいファイルを作成し、ヘッダーを書き込みます。
  await csvFile.writeAsString(headers);

  // リストのURLから動画情報を取得
  for (final url in videoList) {
    final video = await youtube.videos.get(url);
    final title = video.title.replaceAll(',', ''); // タイトル内のカンマを除去
    final thumbnailUrl = video.thumbnails.standardResUrl;
    final linkUrl = url;

    // CSVに書き込み
    final line = '"$thumbnailUrl","$title","$linkUrl"\n';

    // ファイルに追記
    await csvFile.writeAsString(line, mode: FileMode.append);
  }

  // YoutubeExplodeを閉じる
  youtube.close();
  print('CSVファイルに書き込みが完了しました。');
}
