name: Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v3.13.6
        with:
          channel: stable

      - name: Build APK
        run: flutter build apk

  distribute:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Fastlane
        uses: fastlane/setup-fastlane@v2.112.0

      - name: Firebase App Distribution
        run: fastlane firebase_app_distribution_release
        with:
          app_id: track-peak
          app_name: track-peak
          distribution_group: testers
          apk_path: build/app/outputs/apk/release/app-release.apk
