name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.6"
      - name: Create .env.dev file
        run: |
          echo "FLAVOR=${{ secrets.FLAVOR }}" >> env/.env.dev
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> env/.env.dev
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> env/.env.dev

      - name: Build APK
        run: flutter build apk --release

      - name: Deploy APK to Firebase App Distribution
        run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --token ${{ secrets.FIREBASE_TOKEN }} --groups testers

      - name: Build iOS
        if: runner.os == 'macOS'
        run: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath $PWD/build/Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath $PWD/build/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build/ios/ipa

      - name: Deploy IPA to Firebase App Distribution
        if: runner.os == 'macOS'
        run: firebase appdistribution:distribute ios/build/ios/ipa/Runner.ipa --token ${{ secrets.FIREBASE_TOKEN }} --groups testers
