name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        continue-on-error: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.6"
        continue-on-error: true

      - name: Create .env.dev file
        run: |
          mkdir env
          touch env/.env.dev
          echo "FLAVOR=${{ secrets.FLAVOR }}" >> env/.env.dev
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> env/.env.dev
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> env/.env.dev
        continue-on-error: true

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash
        continue-on-error: true

      - name: Build and Distribute Android App to Firebase
        run: |
          flutter build apk --release
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" > ./firebase_service_account.json
          echo "Fileの中身をチェック"
          cat ./firebase_service_account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase_service_account.json
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app 1:1015924011726:android:3e6d8596c2bda420a3169f \
          --groups testers \
          --release-notes "Description of the release" \
          --debug
        continue-on-error: true

      - name: Build and Distribute iOS App to Firebase
        if: runner.os == 'macOS'
        run: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath $PWD/build/Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath $PWD/build/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build/ios/ipa
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/../../firebase_service_account.json
          firebase appdistribution:distribute ios/build/ios/ipa/Runner.ipa \
          --app app-1-1015924011726-ios-2f2d38ddb25065ffa3169f \
          --groups testers \
          --release-notes "Description of the release"
        continue-on-error: true
